Data Protection Page
CM10313-Group-1/tempest pull request #87
Opened 2021-04-14 16:43 UTC by ihussain0910

2021-04-14 16:48 UTC, bridges-wood requested changes

2021-04-14 16:48 UTC, bridges-wood commented on src/main/java/tempest/ui/pages/DataProtectionPage.java
> +                "- Altering the contents of this file may affect the program and cause errors ";
If you wrapped these in `<ul>`, it could look even better.

2021-04-14 16:48 UTC, bridges-wood commented on src/main/java/tempest/ui/pages/DataProtectionPage.java
> +                "- Altering the contents of this file may affect the program and cause errors ";
Instead of 'the user', could you change this to 'you' as if you're talking to the user directly?

2021-04-14 17:15 UTC, Drayz64 commented on src/test/java/tempest/ui/pages/HomePageTest.java
> +    assertEquals(PageNames.DATA_PROTECTION, manager.getCurrentCard());
Could you indent this line please

2021-04-14 17:37 UTC, Drayz64 commented on src/main/java/tempest/ui/GUIManager.java
> +    private final DataProtectionPage dataProtection;
We don't need a local variable of DataProtectionPage. The only reason some of the pages do have a local variable is so they can be used in the switch statement to update them.

So could you delete it and change the line below, to be the same as other pages that don't have a local variable

```java
dataProtection = new DataProtectionPage(state, this),
```

2021-04-14 17:38 UTC, Drayz64 commented on src/main/java/tempest/ui/GUIManager.java
> +                dataProtection = new DataProtectionPage(state, this),
Also state only needs to be passed in if its going to be used - which the data protection page - doesn't so could you not pass in state

2021-04-14 17:42 UTC, Drayz64 commented on src/main/java/tempest/ui/pages/DataProtectionPage.java
> +                "<li>Altering the contents of this file may affect the program and cause errors <ul>";
`Altering the contents of this file`

Are you referring to the store.csv file or the overall project file?

2021-04-14 17:43 UTC, Drayz64 commented on src/main/java/tempest/ui/pages/DataProtectionPage.java
> +                "<li> Any data inputted by the user from within the program will be stored within this file\n" +
`Any data inputted by the user from within the program will be stored within this file`

This won't be the case when Josh's branch is pushed (as weekly goals for each module aren't saved to the csv) so could you change this line to talk about this

2021-04-16 16:31 UTC, bridges-wood requested changes

2021-04-16 16:31 UTC, bridges-wood commented on src/main/java/tempest/ui/pages/DataProtectionPage.java
> +        text = "<html><font size='2'>" + text + "</font></html>";
Fix these tags

2021-04-16 16:38 UTC, bridges-wood approved these changes

2021-04-16 16:38 UTC, merged